import Head from 'next/head'
import Recomandation from '../components/Recomandation'
import Slider from '../components/Slider'
import Steps from '../components/Steps'
import Locations from '../components/Locations'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Foodness</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slider/>
      <Recomandation/>
      <Steps/>
      <Locations/>
    </div>
  )
}
